### ISSUE TITLE
Failed to update use token from web API

### ISSUE THREAD

**Issue by 5StringThunder** [springbok/MLM2PRO-GSPro-Connector#101]
Hello,

when attempting to connect my MLM2Pro I get an error that says "Failed to update user token from web API".

Do you have any thoughts on correcting this?

**Comment by springbok** [comment]
Do you have a subscription for the MLM? 
Have you authorized 3rd party apps via the MLM app?

Can you upload your log file in the appdata\logs sub directory.

**Comment by DDmikey** [comment]
I have this same issue today. The connector worked fine 3 days ago but started giving this message today. I am attaching the error log. I do have a subscription (expires 6/20/2024) and I have authorized the 3rd party app (Awesome Golf). 
[mlm2pro-gspro-connect.log](https://github.com/user-attachments/files/15812247/mlm2pro-gspro-connect.log)

**Comment by springbok** [comment]
Thanks for the log, for some reason it was unable to access the rapsodo site:

Failed to resolve 'mlm.rapsodo.com'

Can you paste mlm.rapsodo.com into your browser and see if you can access the site, you should see the following response:

{"success":true,"message":"Welcome to MLM Cloud API"}

If you do can you try again.
