### ISSUE TITLE
Error connecting to MLM2PRO over bluetooth

### ISSUE THREAD

**Issue by sam-hamer** [springbok/MLM2PRO-GSPro-Connector#105]
I am getting the following error when attempting to connect with bluetooth:

`2024-06-12:18:24:11,804 DEBUG    [bluetooth_device_service.py:66] Characteristics for service {daf9b2a4-e4db-4be4-816d-298a050f25cd} has been discovered: ServiceState.RemoteServiceDiscovered
2024-06-12:18:24:11,804 DEBUG    [bluetooth_device_service.py:77] Subscribing to notifications for service: {daf9b2a4-e4db-4be4-816d-298a050f25cd} characteristic: {02e525fd-7960-4ef0-bfb7-de0f514518ff} on MLM2-M2P13.
2024-06-12:18:24:11,804 DEBUG    [bluetooth_device_service.py:91] Characteristic descriptor is invalid for {02e525fd-7960-4ef0-bfb7-de0f514518ff} on MLM2-M2P13.
2024-06-12:18:24:11,804 DEBUG    [bluetooth_device_base.py:201]  An error has occurred: Characteristic descriptor is invalid for {02e525fd-7960-4ef0-bfb7-de0f514518ff} on MLM2-M2P13.
2024-06-12:18:24:11,820 DEBUG    [bluetooth_device_base.py:117] Disconnecting from device: MLM2-M2P13`

Attached full log.
[mlm2pro-gspro-connect.log](https://github.com/user-attachments/files/15811961/mlm2pro-gspro-connect.log)

**Comment by springbok** [comment]
Have you got the device paired with windows? If so unpair it and try again.

Have you connected to it before via the connector?

When you search for BT devices in Windows what devices can you see advertised?

**Comment by sam-hamer** [comment]
Thanks for the quick response,

- It is not paired with windows, but when searching for bluetooth devices I can see `Blue Z5.50`
- I have not connected to it before with this computer. One thing is that this is running in Windows 11 through Parallels on Apple silicon, so I am not sure if this has been tested/functioning before. I am able to connect to the MLM on my other computer that is running Windows 11 natively.

**Comment by springbok** [comment]
Maybe that is the issue, I've not tested that setup.

Are you able to connect to other BT devices, have you got advanced discovery turned on?

**Comment by sam-hamer** [comment]
Yeah, I have advanced discovery enabled, and I am able to connect other devices. Though, when connecting it seems to send a request through macOS, and it shares the device with the windows VM. Wondering if that might be part of the issue?

**Comment by njbrown09** [comment]
Any update? Having this issue on my m3 mac with parallels.

**Comment by philashworth** [comment]
Did you ever get this working? 
i've been trying with crossover (https://www.codeweavers.com/crossover) that runs GSPro great but when when running the connector it crashes when I try to search for the Rapsodo BT device. The last line I see in the logs is : 
`[bluetooth_device_scanner.py:30] Searching for the following launch monitor names: ['MLM2-', 'BlueZ']`

**Comment by philashworth** [comment]
I've managed to get this working by running the GSPro in crossover and running a version of connector directly on the MAC via Python. I had to strip out all the putting code as this had dependencies on windows video capture
