### ISSUE TITLE
Error connecting to rapsodo

### ISSUE THREAD

**Issue by JPR1212** [springbok/MLM2PRO-GSPro-Connector#107]
I've been trying to connect my rapsodo with this connector. I got it to connect once but ever since then I haven't been able to. I don't have it connected to Bluetooth on my pc. I've tried to connect the launch monitor to my pc as well. When having the rapsodo_BT_serial# and also just the rapsodo_serial # connected, when trying to connect on the springbok connector it gets stuck in connecting mode and just eventually pops up as an error saying that the host has closed the connection. So at this point I'm not sure if I'm doing something wrong to cause this or not. Hopefully this all makes sense I know it's a lot of information to type out. I will upload a photos tomorrow afternoon to show the error. I appreciate your help! @springbok

**Comment by springbok** [comment]
This is normally an issue with BT signal strength or an issue with your BT device, are you using a dongle or inbuilt BT? Do you have access to another BT dongle you can try?

**Comment by JPR1212** [comment]
I don't have a dongle I've been using the internal Bluetooth on the mlm2pro. See the only thing is I have it right next to my pc literally inches from it and still it won't connect.

**Comment by springbok** [comment]
The only thing I can suggest is to get a BT dongle and see if that makes a difference, they aren't expensive so it's worth a try. A number of people have had similar issues and found a dongle resolved the problem.
