### ISSUE TITLE
v1.04.09 Garmin R10 won't connect bluetooth

### ISSUE THREAD

**Issue by Tomatt2** [springbok/MLM2PRO-GSPro-Connector#108]
I am trying to use springbok newest connector v1.04.09 and using Garmin R10, under Garmin R10 BT Launch Monitor column it gets stuck with a yellow box that says "Subscribing...", red box "Approach R10, red box, RSSI: -88, and green box "Battery: 99. Any help would be great. GSPro and wed cam columns all green. Thanks

**Comment by springbok** [comment]
Send me your log file in appdata\logs

**Comment by Tomatt2** [comment]
Will do...at work till 7 am eastern time tomorrow.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tomatt2** [comment]
here is the file you requested...thanks again

[mlm2pro-gspro-connect.log](https://github.com/user-attachments/files/15970429/mlm2pro-gspro-connect.log)

**Comment by springbok** [comment]
Thanks for the file, it can take a few minutes for it to complete setting up the r10, have you left it running to see if it completes the setup? The example file only show a short timeframe, can you do another run and leave it for a few minutes and send me the file?

**Comment by springbok** [comment]
Opening from a shortcut shouldn't make a difference.

**Comment by Tomatt2** [comment]
Ok, I tried a long range blue tooth adapter I ordered from Amazon, it seams to have fixed it, the Garmin R10 is pairing correctly and all boxes green in the column. Played a quick nine holes and it never missed a shot, also very quick from shot to showing up in GSPro. Thank you so much for your help. Will keep testing it but love it so far. Keep up the great work.

**Comment by springbok** [comment]
Good to hear you are up & running.

**Comment by springbok** [comment]
Can you post the log file in the appdata\logs subdirectory.

**Comment by sliceRight55** [comment]
Thanks for your help! log file attached.
I do not have the setting in my bluetooth menu to change from "Default" to "Advanced"

[mlm2pro-gspro-connect.log](https://github.com/user-attachments/files/20661302/mlm2pro-gspro-connect.log)

![Image](https://github.com/user-attachments/assets/870d9378-b59f-44d3-b904-38ea7b69bd06)

**Comment by sliceRight55** [comment]
even after using a separate bluetooth adapter over the weekend, the MLM2PRO connector never leaves the subscribing state and fully connects to the R10. Any other settings I could change to make it correctly connect?
