### ISSUE TITLE
Connector not finding MLM2Pro

### ISSUE THREAD

**Issue by 17hughsc** [springbok/MLM2PRO-GSPro-Connector#111]
I have watched all the videos and still can’t seem to get it to connect. 95% of the time I get an error saying to make sure the LM is within range - which it is within a foot of the pc and has a Bluetooth dongle directly underneath it as well. Sometimes I get an api token problem? I have authenticated awesome golf right before attempting.

Could this be a wifi issue at all? Any help is appreciated! 
![IMG_2706](https://github.com/user-attachments/assets/f4b12d29-730c-446d-b02d-fbeb98071a82)
![IMG_2707](https://github.com/user-attachments/assets/6c56568f-1c88-4942-b270-c11dfc5737a0)

**Comment by springbok** [comment]
So to clarify, have you been able to connect at all? Can you upload your log file in appdata\logs when it fails to connect. If you haven't been able to connect at all, try and do a firmware install via the trouble-shooter, turn off/on and try connect again.

**Comment by 17hughsc** [comment]
I have never successfully connected no. Although I did update the firmware on the mlm2pro and now I am constantly getting “unable to update user token from web api”,  would this have anything to do with my rapsodo subscription being on a free 1 year trial, and not a paid subscription until the trial expires?

**Comment by springbok** [comment]
As long as you have a valid & active account it should work, can you upload the log file in appdata\logs after you try and connect.
