### ISSUE TITLE
not able to click device button 

### ISSUE THREAD

**Issue by khitson** [springbok/MLM2PRO-GSPro-Connector#112]
Trying to set up for the first time and I can't click on the device button to open devices.  All the other buttons work except the device one.
Thanks

**Comment by springbok** [comment]
What launch monitor are you using, make sure to select the correct LM in settings. If a BT LM you don't need to select a device, if an OCR LM make sure to setup your ROI's for your device, once that is done you will be able to select the device. There are plenty of good YT videos explaining the process, see https://www.youtube.com/@JLagGOLF & https://www.youtube.com/@trpl_bgy

**Comment by khitson** [comment]
I’m using the mlm2pro. I got it to work, thanks.  I watched both of the videos you listed before but they both went into the devices and set the rois so that’s what I was trying to do.  I didn’t realize you could just connect and go without setting the rois. Thanks!
