### ISSUE TITLE
Putts  not being sent  to GSPro  ?

### ISSUE THREAD

**Issue by EinarBjorn** [springbok/MLM2PRO-GSPro-Connector#117]
Using webcam putting and Garmin R10 
     - The webcam window is focused when putter is selected
    - The putting seems to work in the Tracker software (getting information on ball speed and HLA in the webcam view and the direction indicator line)
     - Nothing happens in GSPro. No shot log either in the connector app

Used to work fine with v 1.04.09, but hasn't been used for a couple of months. Tried the latest 1.04.10 beta, but have the same issue.

**Comment by wonder99** [comment]
Hmm, there were no intentional changes to webcam putting in 1.04.10beta.
Have you confirmed that putter was selected in GSPRO at the time? 
Can you please attach here the detailed log file from appdata/logs?

**Comment by EinarBjorn** [comment]
This happened with 01.04.09 as well, so it has nothing to do with the beta version.
The putter was definately selected in GsPro and the connector did focus the putting window.
Also, you'll find in the log: "DevicePuttingWebcam Club selected: PT".

[mlm2pro-gspro-connect.log](https://github.com/user-attachments/files/17230172/mlm2pro-gspro-connect.log)

Perhaps some communication issue between MLM2Pro-GSPro-Connector  and ball_tracking ?

**Comment by EinarBjorn** [comment]
Ah, I see. That was a misunderstanding. I'll try to be clear and concise now :)

I downloaded and tested v01.04.09 a few months a go and it worked like a charm. 
I had not used this connector before (I was using the gspro-r10 adapter, which uses the same ball_tracking for webcam putting).

I tested again yesterday after not using the sim for a long time. It first, I had some issues because the inbuilt webcam in my laptop was being used instead of the external USB camera. So I had to modify the camera index in the settings.

Since then, I've had this issue with putting seemingly working in ball_tracking.exe, but not being picked up by the connector and sent to gspro. 

I downloaded the newest beta to see if it was any different, but without luck.

**Comment by wonder99** [comment]
OK I see now.  Unfortunately, I don't have any experience using the R10 with this connector, but maybe @springbok can help.
You might try disabling your laptop webcam, so that that the only choice is the USB camera.

**Comment by EinarBjorn** [comment]
Thanks, but it doesnt look like it has anything to do with the R10 or the webcam though..

**Comment by wonder99** [comment]
Yes, I'm just wondering if the connector isn't handling the choice of camera index=1 properly.  So it might be worth finding a way to avoid the choice, having only 1 camera.

**Comment by EinarBjorn** [comment]
Ahh I see. Good idea :)
Would be a good feature to let the connector choose camera by name or type instead of index (if it's possible), since Windows seems to arrange the indexes randomly

**Comment by EinarBjorn** [comment]
Ok, some additional info. 
I tested again with only one camera (index = 0), but had the same issue.

However, I noticed that the ball_tracker software prints out a line after each shot that seems to be an error message:

![image](https://github.com/user-attachments/assets/d8f435c6-9fc5-4108-ba15-9c452b2961dd)

Digging into the python code, I can see that it's catching an exeption after attempting to post the results to the connector.
![image](https://github.com/user-attachments/assets/da058b05-7228-4889-840a-1a97dd670851)

Any thoughts?

**Comment by EinarBjorn** [comment]
Figured it out. 
Port 8888 is now occupied by a VPN client that I installed recently.
The ball_tracker app is hardwired to post to 8888, would be nice to have it configurable

**Comment by wonder99** [comment]
Nice debugging!

**Comment by EinarBjorn** [comment]
If you have this issue, check if port 8888 is being used:
In command prompt write: 
`netstat -aon | findstr :8888`

If the port is occupied, you'll see something like:
`TCP    0.0.0.0:8888           0.0.0.0:0              LISTENING       1234`

In which case, process 1234 is listening to port 8888.
You can then find the process name with:
`tasklist | findstr 1234`
