### ISSUE TITLE
Mevo+ ROIs issue with V1.04.10 Beta

### ISSUE THREAD

**Issue by agn507** [springbok/MLM2PRO-GSPro-Connector#119]
Not entirely certain this was the issue but had no luck getting the MLM2PRO gspro connector to show the ROIs coming from FS Golf PC app. This would then in turn not send to openAPI. Struggled with this for a few days before realizing I was in fact on the beta and tried v1.04.09 with success.

I do not have the pro package from flightscope which means I have no "Face to path", "Club Path" or "Face to Target" ROIs. I placed these in an empty spot and verification would show "Invalid Value". I can only assume this is what caused the issue with sending values.

Is there a way to exclude these ROIs?

**Comment by wonder99** [comment]
Hmm,not sure how to make ROIs optional. We could add another fs mevo option which excludes those ROIs. But could you also point those 2 ROIs to any other valid number, but then just ignore them in gspro? Like put them both on 'launch angle' or something. It would affect the shot

**Comment by agn507** [comment]
Confirmed that was the issue. Setup again and mapped the ROIs I don't have available to other values. Will there be any side effects with this data being sent to gspro or is it more just informational?

**Comment by wonder99** [comment]
It's just informational

**Comment by agn507** [comment]
Going to go ahead and close this issue as mapping to empty values worked. Might be nice to add some help text there to make it clear or the ability to exclude some ROIs
