### ISSUE TITLE
Exputt Distances not the Same on GSPRO

### ISSUE THREAD

**Issue by jasonklaskey** [springbok/MLM2PRO-GSPro-Connector#121]
Hello Team if this has been asked elsewhere I apologise. I am trying to use exputt with GSPRO using the springbok connector. I have setup all the roi’s and verified the outputs are accurate. I have the camera application open on my 3rd screen which shows exputt and when I put on export the distances are correct, however on GSPRO the put only goes like 1m where exputt it goes 6m. Tried this with a medium distance putt and same thing does not travel as far as it should be on GSPRo, however on Exputt all is correct? I tried different springbok connector versions but get the exact same result. Any advice how to fix this ?

**Comment by wonder99** [comment]
I wonder if it's a units issue--You have both exputt and gspro distance units set to meters?  I think exputt is assumed to be in feet and mph.   Please try that.

**Comment by jasonklaskey** [comment]
> I wonder if it's a units issue--You have both exputt and gspro distance units set to meters? I think exputt is assumed to be in feet and mph. Please try that.

I never even thought of that thank you. Just confirming must both GSPRO and Exputt then be set to imperial or just Exputt and then leave GSPRo on meters?

**Comment by wonder99** [comment]
I believe you only need to set exputt in imperial, but let me know!  I
haven't played around with those things.

**Comment by jasonklaskey** [comment]
Will do it’s night time in SA so will test tomorrow and update . Thank you for the quick response 🙏🏻

**Comment by jasonklaskey** [comment]
Apologies for the late reply everyone I thought I replied the set exputt to imperial worked and resolved the problem thank you🙏

**Comment by jasonklaskey** [comment]
This issues has been resolved
