### ISSUE TITLE
Exputt ROI issues

### ISSUE THREAD

**Issue by Catfish-Billy** [springbok/MLM2PRO-GSPro-Connector#127]
I've spent hours on end trying to get this right, and have only been able to putt a few occasions,  but only for one hole.  When setting ROI's,  I'll get the zones set and hit verify, and it says invalid, or shows an inaccurate value. After tweaking the roi slightly over and over, it will finally verify the roi's and I'll save. Literally the very next hole, I putt, and usually nothing happens, or the speed is way too fast. When I check the ROI's, it shows invalid, or inaccurate data AGAIN. What am I doing wrong? I'm not exaggerating when I say hours have been spent for days on end, before I finally give up out of frustration.  Please, any advice or answers would be greatly appreciated

**Comment by wonder99** [comment]
Hmm I wonder if the exputt window is moving around or changing sizes on you. Try maximizing it's window, set the ROIs from there and test it out.  I have had some weirdness once a while back, but it's fine now.  Also try launching the camera app and getting exputt set up before launching the connector

**Comment by wonder99** [comment]
Also if you can reproduce the issue, attach a screen recording along with the log file from appdata/logs

**Comment by Catfish-Billy** [comment]
I'm about to head out there to give it a go, so I'll try those things now.
But even when it says invalid or give the wrong value when I hit verify,
the roi boxes are still seemingly in the correct location.  I appreciate
the advice.  I'll let you know if I'm successful

**Comment by Catfish-Billy** [comment]
Thank you!!! Sizing up the window must've done the trick. I just got a full
18 in without issues!! Hopefully tomorrow it will be plug and play! Now I
need to buy the controller box!

**Comment by wonder99** [comment]
resolved.  There may be some improvements that could be made in sizing the putting window.  Or it might be an issue with the windows Camera app.
