### ISSUE TITLE
unhandled script

### ISSUE THREAD

**Issue by crazycooter76** [springbok/MLM2PRO-GSPro-Connector#134]
Having issues with the springbok/mlm2pro-gspro-connector. When I go to devices and create a new device named Mevo+, then in the mirror app window name I put FS GOLF PC 2.0.  The instructions say to restart the connector and setup the ROI's.  The problem is that when I restart the connector I get an unhandled exception in script error and cant go any further.  I have attached a picture of the error window.
<img width="306" alt="Capture" src="https://github.com/user-attachments/assets/362eb4bd-3e95-4e3a-8e13-65fbe47f43fb">

**Comment by springbok** [comment]
Make sure the device name doesn’t have any special characters that aren’t allowed in a file name, the device name is used as the file name for the config settings.

**Comment by iamcdn** [comment]
I have same issue.  tried it with 'FS Golf PC' to eliminate the 2.0.  Every time I get back to that setting it get the same crash on start.  doesn't matter the order I start in or leaving out address for FS golf
v1.04.09 mevo+, gspro.

Any other help?

**Comment by iamcdn** [comment]
Fixed it by removing the '+' from Mevo+


> I have same issue. tried it with 'FS Golf PC' to eliminate the 2.0. Every time I get back to that setting it get the same crash on start. doesn't matter the order I start in or leaving out address for FS golf v1.04.09 mevo+, gspro.
> 
> Any other help?

**Comment by springbok** [comment]
Good on getting it going, as I mentioned any special characters not allowed in a filename should not be used in the device name. I’ll update the code to filter them out in future to prevent confusion

**Comment by springbok** [comment]
V1.04.16 should now strip out any invalid characters.
