### ISSUE TITLE
Not getting Roi for Exputt - Screenshot error

### ISSUE THREAD

**Issue by actionsnake** [springbok/MLM2PRO-GSPro-Connector#137]
I am getting an error when I try to set up the ROI for exputt in the connector. Exputt for itself is working, it seems the error is a system error of windows but I have no idea where the problems is.
![Screenshot 2024-11-21 173957](https://github.com/user-attachments/assets/20afc153-11c1-4508-833c-273b068960cd)

**Comment by wonder99** [comment]
I see your camera window is called kamera with a k.  Change the window name in the settings, that should fix it

**Comment by actionsnake** [comment]
ok, its working, thank you. now i have to setup getting the right distances in gspro and exputt. the first test had a putt distance of nearly 7 metres in exputt but only a few cm in gspro. any idea?

**Comment by wonder99** [comment]
Yeah check your units in exputt. I think the connector assumes miles per hour and feet.

**Comment by actionsnake** [comment]
will check it tomorrow. thank you.

**Comment by wonder99** [comment]
No, sorry there isn't.
