### ISSUE TITLE
GSPro connection doesn't work with Uneekor

### ISSUE THREAD

**Issue by khthe8th** [springbok/MLM2PRO-GSPro-Connector#145]
GSPro Connection doesn't work with Uneekor on GSPro V3 and MLM2Pro-GSPro-Connector_V1.04.16, it shows not connected. 

My guess is because the GSPro connection is now called "Uneekor Connect" and not "APIV1 Connect". 

I have Multiview open, GSPro open, GSPro Uneekor connect is connected, and the connector can read my ROIs. But I get a "GSPro Connect Error - Error while trying to connect to GSpro. Make sure gspro API connect is running. Start/restart API Connect from GSPro. Press 'connect' to reconnect to gspro."

I tried to rename from APIV1 connect to "Uneekor Connect" inside the MLMconnect settings to match what the window is called, but that doesn't work either.

**Comment by wonder99** [comment]
To use this connector, you must switch your GSPRO license to OpenAPI.  At
that point, the GSPRO connection will be called APIV1 Connect.
You can switch your licence freely here
https://gsprogolf.com/convert.html
- Paul

**Comment by khthe8th** [comment]
Ah thanks, missed that in the wiki I guess!
