### ISSUE TITLE
Can Connect Device and GSPro But Shots Don’t Show Up on GSPro

### ISSUE THREAD

**Issue by Asykes3** [springbok/MLM2PRO-GSPro-Connector#146]
Hi all,

I have gone through the necessary steps and have configured the ROI’s, I can get the device connected to iPad/Airplay app on PC, as well as I can launch GSPro and connect to the API and all shows green, however when I go to make a shot, it is still only registering on the iPad/MLM2 app and does not register the shot data on the GSPRo app. Any help would be greatly appreciated!

**Comment by wonder99** [comment]
My guess is that the name of your screen mirror window is not set correctly
in the connector.

Please post here screen shots of your connector window, and its devices and
setup screens.
Also, the log file from the connector's appdata/logs directory.
Thanks

**Comment by Asykes3** [comment]
![IMG_7521](https://github.com/user-attachments/assets/f891d1c9-0db6-4361-ae4a-7248eaeeb476)
![IMG_7522](https://github.com/user-attachments/assets/057e74ba-5e22-4b74-9902-5ebd859d0301)
![IMG_7523](https://github.com/user-attachments/assets/36f3ca3b-758a-4d29-88e5-ed114df70599)
![IMG_7524](https://github.com/user-attachments/assets/ed3a4071-2df4-416a-b381-83d0973e44ce)
![IMG_7521](https://github.com/user-attachments/assets/a3716860-c312-42b1-83cf-ba3f10539be3)
![IMG_7522](https://github.com/user-attachments/assets/6593baab-41cd-41d3-95b4-72020841f6b1)
![IMG_7523](https://github.com/user-attachments/assets/b926c614-165e-40a8-805a-ca0f4267d0c4)
![IMG_7524](https://github.com/user-attachments/assets/a81c1876-66e9-4195-ae2e-545fd4a6cc5d)

I’m not incredibly tech savvy, so I just took pictures of everything and am attaching here. Let me know if there’s anything else I can do to help. The only thing I was also not sure of is all of the setup videos I’ve seen seem to be from a different version of MLM2Pro range setup/look. When I configure the ROI’s I can see that sometimes it doesn’t read all of the data correctly. Not sure if it’s an all or nothing type of issue here.

**Comment by wonder99** [comment]
You do have the camera mode set to stationary, right?

**Comment by wonder99** [comment]
Also, it's helpful to see the log file. Go to the folder where you're
running the connector from and look for that appdata/logs directory

**Comment by wonder99** [comment]
Also, can you send a picture of the screen where you've positioned the ROI
boxes?

**Comment by Asykes3** [comment]
![ROI Screenshot](https://github.com/user-attachments/assets/bab7bb74-cb9d-4270-b517-18d31eb4ae07)
[mlm2pro-gspro-connect - log data for github.txt](https://github.com/user-attachments/files/17963418/mlm2pro-gspro-connect.-.log.data.for.github.txt)

I believe these are the two items you requested. I am not sure what function you are asking if it has the camera mode set to stationary, or how I would check to see if that is the case or not. Thank you very much for your help so far!

**Comment by wonder99** [comment]
Thanks for the files, and the boxes look good. So if you hit a shot and
click Verify, the values are not read correctly?

**Comment by wonder99** [comment]
Just thinking, why not use the direct Bluetooth connection between gspro
and the MLM2PRO?

**Comment by Asykes3** [comment]
it doesn't always read correctly. Sometimes it will mistake things like a 6 for a 5

**Comment by wonder99** [comment]
Yes the iPad uses such a tiny font, you must use a very good screen mirror
app to preserve it as much as possible. I'm not sure which mirror app works
best, but direct Bluetooth is a far better way to connect them. You just
may require a Bluetooth extender because the antenna in the MLM is very
weak on some units (like mine).  Once that is solved direct BT perfect

**Comment by Asykes3** [comment]
I'm not sure how to direct bluetooth it like you are talking about. any assistance much appreciated

**Comment by wonder99** [comment]
Looks like we don't have documentation for that yet. Unfortunately I'm out
for the evening now but you can play around with it. Select wrap Soto BT as
your device and move your MLM directly beside your PC.

**Comment by wonder99** [comment]
On your iPad, you'll first need to launch the MLM app and authenticate a
third-party application like awesome golf. Then close down the app and
continue on the PC

**Comment by Asykes3** [comment]
I was able to get direct to BT to work! Thank you for your help!

**Comment by wonder99** [comment]
Great!! Np
