### ISSUE TITLE
Connector and GS Pro does not get data from tracking ball when putting

### ISSUE THREAD

**Issue by igd001** [springbok/MLM2PRO-GSPro-Connector#151]
It seems that the connector is not gettig data from the tracking ball app when putting. My configuración used to work correctly with GS Pro V2 and the connector V1.04.09 with a garmin R10 but during the last weeks I have not used the putting app. The only change I am aware of is the upgrade of GS Pro to V3. Today i updated the connector to V1.04.16 and I continue having the same issues. The putting window identify the ball and the speed and launch angle when i take a shot but the connector and GS Pro does not get any data. The following pictures show the putting window and the ball tracking app where a shot of 5.68 MPH and -0.63 degrees is registered but not registered in the connector not in GS Pro. The last picture is the configuración of the putting app![image](https://github.com/user-attachments/assets/d2c47d73-59bb-48ca-933b-e5447ac53ae1) 
![image](https://github.com/user-attachments/assets/104b1fc0-83a2-4998-9b50-6c0878a32af0)
![image](https://github.com/user-attachments/assets/f838e8cf-e0d6-4834-9f30-0c167623e494)

**Comment by igd001** [comment]
It seems the problema was related to socketexception 10013 error (System. Net. Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden) most likely because of a conflict with another app using the same ports or sockets.

I ended up uninstaling an application that manage an UPS that was runing in the background in my PC and the connector and GS Pro are working correctly now.

**Comment by wonder99** [comment]
user found resolution
