### ISSUE TITLE
SC4 issue - when spin rate is blank shot registers as Error/Failure

### ISSUE THREAD

**Issue by m3kessler1** [springbok/MLM2PRO-GSPro-Connector#154]
I am using a SC4 launch monitor.  In order for shots to register on the monitor with a wedge you have to select that club type in the MySwingCaddie app.    If you don't select a wedge, the shots don't really register. 

When you select the wedges in the App the back spin comes through as empty.   

The rest of the shot data comes through ok on the connector, but the back spin is being set in ball_data.py to invalid_value = 9999999.  That seems to then see the shot as  Failure and it isn't sent to GSPro.

I have been looking at the ball_data code and see where there is some correction items for spin and out of bounds(limits) based corrections.  But it seems that is being trumped based on an error msg then setting the invalid_value for the data item. 

I might work on a fix to provide, but I just started playing with the tool, and wondering if I am missing something, might be a quicker fix for someone else.

**Comment by wonder99** [comment]
Well, without back spin or total spin, you don't really have enough
information to produce a shot in GSPro. I'm not sure what kind of
workaround you are envisioning.

**Comment by m3kessler1** [comment]
I understand what you are saying, but when I looked at the code there is already some code in there for the SC4 to do some spin and Launch Angle corrections.  

Lines 327-337 in the ball_data.py

If spin is >=0 it sets it to 5000 and if VLA is >= 0 it sets it to 36.   But it looks like this depends on GSPro sending the club selection over via the API.  PW-LW uses this.   There is no ROI to detect the club using the Mobile app display, as far as I can tell.

If this was just applied any time Back spin was blank (no matter the club) and the other ROIs are valid then that would satisfy what I am looking for.   I have been testing this out prior to even buying GSPro, using FooGolf and the chip shots won't even send.  

My whole goal is to be able to play a full round on the simulator using SC4, right now in E6 Connect, chip shots are always showing like 12,000+ RPM and will spin back off the green even from like 10 yards, makes game play annoying, and then no putting.   So excited to use this with Webcam putting and even just basic chipping would be awesome.

**Comment by m3kessler1** [comment]
FYI.  For line 329 in ball_data.py   I removed the part that was dependent on club. and tested and it seems to do what I was looking for.    I am sure this works fine when connected to GSPro and receiving Club selection.   I just wasn't ready for that. 

Possibly could just make a change that if GSPro is not connected, the club selection could come from an ROI in the Screen Mirror App.   

I will close because probably not an issue, but more of a nice to have for SC4 peeps testing this out.
