### ISSUE TITLE
Connector with Skytrak+

### ISSUE THREAD

**Issue by Panther1010** [springbok/MLM2PRO-GSPro-Connector#159]
Is it possible to add a parameter for delay ?  The Skytrak+ Numeric values doesn't all come back at the same time and the Skytrak+ detail at bottom goes away when you hit and then comes back but when it comes back, the numbers are not all displayed at the same time.  This is causing incomplete data to be sent to GSPro.  It seems to be reading numbers good but the delay is throwing things off.

![image](https://github.com/user-attachments/assets/e45d70d7-1ae8-4996-a751-b9df5dcecff9)

![image](https://github.com/user-attachments/assets/ec92f56d-64ee-45c5-bcbb-04e8e1f37a9c)

**Comment by springbok** [comment]
Same issue as issue [153](https://github.com/springbok/MLM2PRO-GSPro-Connector/issues/157)
