### ISSUE TITLE
Not Picking up shots. 

### ISSUE THREAD

**Issue by FastFarming** [springbok/MLM2PRO-GSPro-Connector#52]
Hi, 
Ever since the last update to rapsodos app and firmware the connector seems to be producing several errors preventing the shots from playing in gspro. Some shots are picked up by the connector but most fail, it seems very inconstant on what shots and and succeed with them being different each time. I have also noticed the connector seems to duplicating some of the failed shots with the duplicates also failing. I'm using android and scrpy to cast and has worked perfectly until recently. Any help to resolve this issue would be appreciated.

**Comment by springbok** [comment]
Took ages to fix this issue, here is a link to the latest release if you want to test it. https://1drv.ms/u/s!Agx7aYfjrZJ8oEPmWARrMsEcv-hb?e=b36vZp

**Comment by JBrapgolf** [comment]
Tested out the new version and wow, so nice!!  I didn't have one misread!!  Thank you!

**Comment by springbok** [comment]
That's great to hear, pleased it worked well for you.
