### ISSUE TITLE
Connecting Mevo+ with ExPutt

### ISSUE THREAD

**Issue by Moreck1** [springbok/MLM2PRO-GSPro-Connector#53]
Getting GSPro Connect Error.  Keeps referring to API Connect.  Flightscope uses "Flightscope v1.9".  Did API Connect get hard coded?  I entered "Flightscope v1.9" in the field GSPro API Window Title.  Putting setup with ExPutt and Mevo+ Launch Monitor both green and running.  Just can't get GSPro to connect.

**Comment by Moreck1** [comment]
I tried going to the GSPro settings/game and hitting the Reset GSPro Connect button but FlightScope v1.9 opens.  It must be because Mevo+ users download a different license from GSPro versus Rapsodo users.

**Comment by springbok** [comment]
Yes I'd say that is the case although I'm not sure, you can check the Mevo+ discussion and maybe ask fellow Mevo users.

**Comment by Moreck1** [comment]
I just wanted to pass the issue along, since the new announcement states, "MEVO+ is now supported."  MLM2PRO-GSPro-Connector doesn't currently work for Mevo+ Users.  The launch monitor can map FS Golf PC 2.0 or Flightscope v1.9, but GSPro Connection will not connect and go green.  Error Message: GSPro Connect Error.  "Error while trying to connect to GSPro.  Make sure GSPro API Connect is running.  Start/restart API Connect from GSPro.  Press 'Connect' to reconnect to GSPro."

With the launch monitor connected and ready, it's not much use if the GSPro Connection can't connect.

**Comment by springbok** [comment]
It does support it but you need to decide what connection method you want with GSPro, I think you would need to change your license to the GSPro API if you want to use the connector. As I mentioned I don't have a MEVO so am not up to speed with the eco system, I've added the ability to recognise FS Golf and send the data to the API window.

**Comment by Moreck1** [comment]
Thanks for the reply.  That's exactly what I was considering.  I went to re-download GSPro and saw the option of Open API.  It's my misunderstanding of how I need to connect with this software.  Great work on getting this to functionality.  From what I see, it looks like it would work great if not for me having the wrong version of GSPro.

**Comment by Moreck1** [comment]
Connects to Mevo+, but you need to have Open API version/ license of GSPro.
