### ISSUE TITLE
OCR doesn't like the "8"

### ISSUE THREAD

**Issue by arcticdouble** [springbok/MLM2PRO-GSPro-Connector#54]
I am getting many failed shots due to the OCR failing anytime an "8" shows up in swing speed or club speed.  I swing in the 80mph range alot, so most of my iron shots fail.  

Is the OCR built in, or is there OCR software on my computer already that I could update?

**Comment by springbok** [comment]
Are you using Android? The issue is caused by the white bar behind some values in the updated Rapsodo app. You can test this version:

https://1drv.ms/u/s!Agx7aYfjrZJ8oFsN4vqutHx9L76v?e=gvJrhD

**Comment by arcticdouble** [comment]
thank you for your reply, springbok.  I really can't say enough about your efforts!  I will donate tonight.

I am using an iPad 10.  I am using 5kPlayer as the mirroring application, and have a suspicion that it is poor resolution of the screen share that is causing the misread of the ocr, but just a suspicion.  

I made the boxes very tight to the numbers later this evening, and had successful reads.  So, again, it might just be user error. I'll play a round of 18 tomorrow morning, and let you know if this issue is resolved as well.  Just weird that the other boxes read 8's without being drawn super tight around the numbers, but club speed and ball speed seem to have issues with the 8's (I think they read as zeros, a couple reads that had 82 read as 2 cause this suspiction), and sometimes 9's and 6's, if the boxes are drawn liberally.

Again, thank you for your work and attention, and apologize if this is all just user error.

**Comment by springbok** [comment]
Thanks for the donation and kind words its much appreciated. Give the new version a try and see how you go, also don't make the ROI boxes too small. If you still have issues post an image of your ROI screen and also send me the log file in the appdata\logs directory.

**Comment by arcticdouble** [comment]
![Screenshot 2023-11-18 161859](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150534136/b46e2bc2-a02f-4501-8160-b3fa2cf55a01)
 

Here is an example of the issue I am having.  The OCR is not being accurate.  0.1 will be read as 1.  81 will be read as 1. 6's are read as 0's.  I've tried all sorts of box locations, I can fix it to get it to read right, but then a shot or two later, it has some other number it wants to read incorrectly.  

Any thoughts?

**Comment by arcticdouble** [comment]
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150534136/3d3bc234-f6b1-45d1-8edb-91e2624f1d30)
I rearranged the location of the data to see if that made a difference.  Launch Direction was the misread on this one.

**Comment by springbok** [comment]
Which version are you running?

Can you send me the log file in the appdata\logs directory.

**Comment by arcticdouble** [comment]
I am running the new version posted in the issue resolution to the mis hit issue.

[mlm2pro-gspro-connect.log](https://github.com/springbok/MLM2PRO-GSPro-Connector/files/13402007/mlm2pro-gspro-connect.log)

**Comment by springbok** [comment]
The latest Rapsodo app update caused issues with the OCR for Android devices due to the white bar behind some values. So you need to be running v1.01.15 which fixes this issue.

**Comment by springbok** [comment]
Sorry I didn’t see your reply, can you install the version from the link I posted earlier to make sure you are running the latest, if you can then check the version via the “i” toolbar button.

I’ll have a look at your log file when I get a chance thanks for sending it.

**Comment by arcticdouble** [comment]
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150534136/26da2a4b-754a-4c3b-a02e-894b083bbf3e)
I downloaded version 1.01.08 and it did better.  Gets the 8's but missed the negative sign on the launch direction.

I will reinstall 1.01.15 and give it another go with a clean install.

Thank you, again!

**Comment by arcticdouble** [comment]
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150534136/ba1812fd-5b1a-4af6-8550-eb983945a2ba)
This is just the first shot, but I can't get it to see the 2 in the spin axis box.

**Comment by arcticdouble** [comment]
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150534136/513a2438-34f7-4039-b892-9afab64a69f5)
OK, calling it quits for the day.  Here is one last one from 1.01.15, didn't like the 8's in the spin.

I'm finding that when there is a 2 in the spin axis or launch angle, it will cause an issue.  Also it reads 8's in the spin axis as 0.

Let me know if there is a better way I can collect data for you.  I'll attach the latest log file.

Have a good night, from Alaska!
[mlm2pro-gspro-connect.log](https://github.com/springbok/MLM2PRO-GSPro-Connector/files/13402089/mlm2pro-gspro-connect.log)

**Comment by springbok** [comment]
Thanks for the images, is that what the image on the mirror looks like, the resolution does not seem very good and the OCR would have trouble reading it as its trained for a higher quality image. Are you able to try the AirPlay app and see if it makes a difference? You can download a trial version of AirPlay.

**Comment by arcticdouble** [comment]
I cannot find Airplay in the Windows 11 store.  I have it on another computer that runs Windows 10, but have yet to find it for windows 11.  Is there another way to install it?

**Comment by springbok** [comment]
I use windows 10 so not sure why it’s not available on windows 11. Maybe
it’s not being developed anymore.

Any other mirror apps if you search the windows 11 store?

It’s strange because a lot of people have used 5kplayer without any
problems. Is the resolution as bad as it looks in the images you sent me?

**Comment by arcticdouble** [comment]
Ok, closing this issue. 5k player just doesn't have the resolution to perform well with the ocr,  but once you can find airplay by Hao Cai on the Microstation site website, the store app doesn't show it, you are good to go. 

Thank you for your help on this one!

**Comment by arcticdouble** [comment]
Sorry didn't hit the close button on the last post
