### ISSUE TITLE
Chip with a ball speed of 19 reading as 193

### ISSUE THREAD

**Issue by jjmanthei05** [springbok/MLM2PRO-GSPro-Connector#55]
I have had multiple chips last night that registered as 19 for ball speed but came through gspro as 193.

**Comment by springbok** [comment]
This is a result of the OCR misreading and adding an extra digit, I try and correct this as much as possible but in some cases like these it’s not possible as the ball speed falls below the threshold. Not much I can do about it other than tighten the threshold but then I will be correcting genuine ball speeds.

**Comment by wonder99** [comment]
I was wondering if he's using an older version of the connector, before
some of the metric manipulation was improved?
Paul

**Comment by jjmanthei05** [comment]
Sorry meant to post in the original issue log. I am on the most current version of the connector. if there is nothing that can be done, that is fine. Just wanted to post in case this wasn't known.

**Comment by springbok** [comment]
Are you using Android or iOS?

I have a new version I will release in the next day or two, you can download and try it to see if it improves things for you:

https://1drv.ms/u/s!Agx7aYfjrZJ8oGhnFYzyiFwlba5Q?e=0kaI8w

**Comment by jjmanthei05** [comment]
I am using IOS. I will download to check it and let you know. Thanks for the quick response.

**Comment by springbok** [comment]
There is anew beta release that have worked well for everyone thus far:

https://1drv.ms/u/s!Agx7aYfjrZJ8omovE3iQwJ63ENES?e=VOjpP4
