### ISSUE TITLE
Cloned shots in GSPro

### ISSUE THREAD

**Issue by brian4golf** [springbok/MLM2PRO-GSPro-Connector#62]
Hi,
First off thanks for spending the time to design the gspro mlm2pro connector, appreciate it a lot! I am new to the connector as I just got gspro and have been using the proprietary courses in Rapsodo. I have gotten everything setup properly and verified the launch metrics in the connector interface. My issue is when I hit a shot the software repeats my exact shot for the 2nd and advances it automatically then stops and I can then take over control but am hitting the 3rd shot now. Sometimes the system repeats twice after the initial shot and I then get control to hit the 4th shot. 

Any help with getting this resolved is very much appreciated.
Thanks,
Brian

**Comment by springbok** [comment]
This can happen if you haven’t set the range camera to stationary in the Rapsodo app.

**Comment by brian4golf** [comment]
Thanks I can confirm it was a user error at it works perfectly now! May I ask when you would use stationary mode versus the ball flight mode? Is stationary for inside versus outdoor perhaps. I tried to google and couldn't even find anything on stationary mode just stumbled upon it.

**Comment by wonder99** [comment]
Great.

The choice is only personal visual preference.
