### ISSUE TITLE
Ball Height and Carry

### ISSUE THREAD

**Issue by FastFarming** [springbok/MLM2PRO-GSPro-Connector#63]
Hi, I'm having some issues with the connector, the data seems to be accurate from the mobile to the connector GUI however in GSPRO many of the shots are coming out quite low and have the incorrect carry as a result.  Could anyone point me in the right direction to resolve this issue?

**Comment by wonder99** [comment]
Can you give me an example?  What is the VLA on the mobile, in the connector, and in GSPRO?  Is it off like by a decimal point?
Can you send a screen shot of your ROI boxes?

**Comment by FastFarming** [comment]
Hi, thanks for the response it doesn't happen on every shot but a large proportion of them..  And yes the VLA does seem to be out by a decimal place.. It is the same in the connector GUI as gspro.

ROIs: 
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150730423/ba09e0a4-7cb8-40b7-a705-be912509d76f)
GSPRO:
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150730423/9cf17c47-69bb-438d-9756-72aac2c96b85)
Rapsodo App: 
![WhatsApp Image 2024-01-09 at 21 08 43_7fd193bc](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/150730423/89f92500-ddd1-485f-bfeb-e5dfd1a07aef)

**Comment by wonder99** [comment]
Shrink your boxes down to be more like this (red)
![box](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/5347771/d9f02df4-9e19-4594-9534-445ff70ba56a)

**Comment by FastFarming** [comment]
That seems to have worked a treat thank you! Didn't realize it was something so simple..
