### ISSUE TITLE
MLM2 GSPro double hit reads

### ISSUE THREAD

**Issue by willschabel** [springbok/MLM2PRO-GSPro-Connector#64]
I'm noticing quite often while playing when I hit the ball will read correctly, settle, and then re-apply the same hit again.

I'm assuming this is happening due to a change on the screen of some sort causing the program to re-read the same data twice or more.

A good stop gap solution maybe to add a setting to stop and start the data recognition with a keybind. Obviously when enabled it will wait for a change, but once enabled will automatically disable after the first read, this will allow the user to enable reading once they are ready to hit again.

**Comment by wonder99** [comment]
You should retry with version 27.  It has a double-shot protection as well as a pause button, which was meant to be used when you're intentionally changing something in the MLM app

https://1drv.ms/u/s!Agx7aYfjrZJ8omovE3iQwJ63ENES?e=VOjpP4

**Comment by willschabel** [comment]
Awesome, I'll check it out.
