### ISSUE TITLE
"Double" read issue

### ISSUE THREAD

**Issue by Seibs14** [springbok/MLM2PRO-GSPro-Connector#65]
I'm using the mevo+ with this connector. Generally works well, however, about once or twice a round I'm having the connector send a ghost shot along with the actual shot. This ghost read is not in FS Golf, so it's something the connector is doing. 

Specifically, I'll hit a shot, my ball in GSPro will immediately roll anywhere from 5 feet to 20 yards, and then the actual shot will send in a completely random direction. I've had a few tee shots, for example, that have rolled forward a few feet and then gone 270 yards in the completely wrong direction.

**Comment by wonder99** [comment]
Can you send us the log file (in the appdata/logs subdirectory) and a screen shot of your ROI boxes?

**Comment by jirvin7** [comment]
I am having the same problem. Was in a practice session in GS pro. I have a mlmpro2. The only time i was getting a double read was when there was a failure on reading one of the screenshots . If the was sussesful the first time then it was good but if there was one failure there would be a double shot. (barely leaning to code, or i would love to help but im early early stage) but if you can make the code read to the api on gspro once everything read was sussessful i would say that would solve the issue. Seems that no matter if there was a failure on reading the code it would shove it out to the api and do the shot with the data it has then do the double shot once it got the data successful.

**Comment by springbok** [comment]
There are lots of anti ghost shot code in the connector and the latest version has added additional protection and in testing for most people has eliminated this issue. What version are you using?

The latest version is v1.01.31 which has not been released as yet, if you want you can download and test it.

https://1drv.ms/u/s!Agx7aYfjrZJ8pGERC9cV7wLySIaw?e=LfhYs8

**Comment by jirvin7** [comment]
Still the first, ill update and see if it fixes it

**Comment by Seibs14** [comment]
So, since posting this, I had 6 holes where it did this every shot but I didn't get any screen shots. I adjusted my ROIs slightly and moved a hearer, and it has been flawless since.
