### ISSUE TITLE
Duplication of Shots n MLM2 Pro Connector

### ISSUE THREAD

**Issue by shane7ramsey** [springbok/MLM2PRO-GSPro-Connector#66]
I am having an issue with MLM2 Pro Connector where there is a duplication of shots. It will sometimes do 2,3, or 4+ shots. I can see the connector shows that the shot is duplicating, with only the launch angle being the difference between them. Sometimes it even spits out a crazy angle that doesn't make sense. I tried deleting and reinstalling the connector but have had no luck. I am using the latest version I have seen which was 1.20 I believe.

**Comment by springbok** [comment]
If you are using v1.01.20 then you need to put the range camera into stationary mode, there is a newer version that works in both modes although we still recommend stationary mode. Here is a link to the latest beta version if you want to try it out.

https://1drv.ms/u/s!Agx7aYfjrZJ8pEZUYIJhb39xdyX7?e=IOXaof

**Comment by springbok** [comment]
Great to hear its working for you now.
