### ISSUE TITLE
ExPutt - Camera window name with french character

### ISSUE THREAD

**Issue by hgspch** [springbok/MLM2PRO-GSPro-Connector#78]
I have set the Camera App Window Title to `Caméra`.
Which is the default name in french, note the special character.
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/7132df69-34a6-47bc-abcd-71ac3135739a)
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/cdab7151-8581-4c6d-91d2-3242560112ed)

The connector does not find the window.
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/dd8ece5a-b50b-4a49-bc72-ff4a4bdb2230)

version : MLM2Pro-GSPro-Connector_V1.01.32

**Comment by springbok** [comment]
Can you try and set the name directly in the config file in appdata\putting_settings.json

**Comment by hgspch** [comment]
Tried to edit putting_settings.json, but the character  "é" is not read correctly.
Although the file appears to be encoded as UTF-8.
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/e9039844-f846-42fd-bf29-c90aea93f653)

**Comment by springbok** [comment]
In my putting_settings.json I see this if I add the accented e, 
```    
"exputt": {
        "window_name": "Cam\u00e9ra",
        "window_rect": {
```

**Comment by hgspch** [comment]
Yes, it works now with the accented character.
Thank you.
