### ISSUE TITLE
Use only ExPutt

### ISSUE THREAD

**Issue by hgspch** [springbok/MLM2PRO-GSPro-Connector#81]
### Discussed in https://github.com/springbok/MLM2PRO-GSPro-Connector/discussions/79, 
*** **irrelevant part removed, and others modified for clarity** ***

I can't manage to use ExPutt as the only connector, having nothing set in the Connector > Launch Monitor section.

Everything seems correctly set up for ExPutt, "Putter" and "Putting Mode" are selected in GSPro.
Except no "Putter" label shows up in the connector bellow "GSPro connection".

No ball data get displayed in the Springbok connector, and nothing happens in GsPro.

I need to have just ExPutt in the Springbok connector, to use only Exputt to practice putting.

I guess there isn't much missing for it to work?

Thanks !

![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/b8a62101-dac7-4946-ac49-8a15608f46d3)
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/79b68534-2400-4e3b-991d-948a874f5a18)
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/fd5122ed-6a1c-4b1b-b8d4-ad017800b9ff)
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/0d43afd3-78e6-4ea0-88c7-2bde84c00fcd)
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/74004/44016a83-2ef7-44c5-aebb-8cb6646e470e)

**Comment by springbok** [comment]
Sorry at the moment it won't allow putting to be used on its own, will look at adding it to the connector.

**Comment by springbok** [comment]
This is a very early version of the updated connector that will allow you to use ExPutt standalone. Please note I've done very limited testing so expect problems.

https://1drv.ms/u/s!Agx7aYfjrZJ8qTq7_iurLMWyixZ5?e=X71Zh3

**Comment by hgspch** [comment]
Thank you very mutch.

The connector does not start on my pc. 
No window is showing.
No error in the log file.
[mlm2pro-gspro-connect.log](https://github.com/springbok/MLM2PRO-GSPro-Connector/files/14583062/mlm2pro-gspro-connect.log)

**Comment by springbok** [comment]
Sorry, there is an issue if the LM is set to the MLM, I’m working on a fix, but you could manually set the LM to R10, edit the appdata\settings.json file and change the line to:

 

"device_id": "R10",

 

Hopefully, it should start for you this time.

 

I’ll post a link of the update when I have it available.

**Comment by springbok** [comment]
I'm away at the moment so unable to fully test this release, if you find other issues it may have to wait till I get back.

https://1drv.ms/u/s!Agx7aYfjrZJ8qTtPFGWLCuGsF0OW?e=rlwCWT

**Comment by hgspch** [comment]
It works fine, thanks again. I trully appreciate your support.

**Comment by springbok** [comment]
Great to hear its working. I close this issue, let me know if you have any problems.
