### ISSUE TITLE
Android Cast

### ISSUE THREAD

**Issue by Charleybeat** [springbok/MLM2PRO-GSPro-Connector#83]
Hi All , I’m using the Android Cast application from Ipad to windows Pc. I got a nice mirror of the tablet that would be ideal to use the Ipad to the pc for the connector.

However, in the connector (device) I can’t retype exactly the name of the window I see there is an icon (emoji) on the Android Cast window. 
Is there a way to copy paste that name or change the window title?

i’m not using Airplay cause I want to use Direct Connection on the MLM2Pro

**Comment by wonder99** [comment]
Android cast to cast an Ipad?!?  I'm not sure how you're doing that :)

I know we found a way to deal with the french-accented 'e' in the window name for Camera--I think we were able to put the unicode character in the settings.json or something.  Maybe we can find the unicode character for the Android Cast icon.

I can't seem to find the example unicode fix we found for Camera.

**Comment by Charleybeat** [comment]
Yes the Android Cast has to installed on Ipad and on your PC. Then you use a USB from Ipad to PC and you can have the mirror in that app. It looks great.
I can send you a snapshot if you want.

I don't see an issue about the french accent, issue is more the emoji (icon) from android in front of the title.

**Comment by wonder99** [comment]
Do you mean airdroid cast?
Please send screenshot.  For some windows (e.g. Chrome) you can rename the window, which would make it easier

**Comment by wonder99** [comment]
this was the french issue, though I can't find the solution.  
https://github.com/springbok/MLM2PRO-GSPro-Connector/issues/78

**Comment by Charleybeat** [comment]
I have also Exputt , but all my set up is in English so I would not see an issue on this.

I will send you a screenshot for the Android Cast window title I was talking about

De : wonder99 ***@***.***>
Envoyé : 5 mars 2024 15:48
À : springbok/MLM2PRO-GSPro-Connector ***@***.***>
Cc : Charleybeat ***@***.***>; Author ***@***.***>
Objet : Re: [springbok/MLM2PRO-GSPro-Connector] Android Cast (Issue #83)


this was the french issue, though I can't find the solution.
#78<https://github.com/springbok/MLM2PRO-GSPro-Connector/issues/78>

**Comment by Charleybeat** [comment]
![Screenshot 2024-03-05 160231](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/162368342/5949257a-d013-4fc4-b8d8-fd8fdd958284)

see screenshot of the window title

**Comment by Charleybeat** [comment]
![Screenshot 2024-03-05 175703](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/162368342/bcfb42d0-e4a4-40bc-9fd2-641698aa3096)

**Comment by Charleybeat** [comment]
Issue resolved 

name of the window is actually not what it showed on the bar

Also need to put the Cast in Full Screen before opening the ROI

I have been able to connect and use gspro

let me know if you need anything

**Comment by springbok** [comment]
To clarify, are you still having problems or have you resolved all the issues? I'm adding a function that will display the Window titles of all open Windows to make it easier for people to find the correct value.

**Comment by Charleybeat** [comment]
Hi Etienne,

Windows title issues is now fixed : title is AirDroid Cast and ROI can only be used when on full screen mode. I can send you a video if needed.
I’m connected on USB-C from ipad to pc.
Direct wifi to MLM2Pro.

I noted different issues today:


  1.  exputt: nothing was read into the connector
I reboot and then reconnect everything I did 2 holes and then nothing was going into the connector again. Haven’t found the solution, will try again tomorrow


  1.  ROI for launch angle : lots of errors
I need to rehit shots

  2.  ROI for Ball speed : lots of incorrect reading
example : 39 is read 139 in the connector
Happening only when chipping with two digits.


  1.  Disconnect from MLM2Pro to Ipad
I can’t find the correlation how sometimes it never disconnect and sometimes it disconnect every 3 shots. That is a Rapsodo major issue.

Let me know your thoughts.

Cheers




Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Etienne van Tonder ***@***.***>
Envoyé : Wednesday, March 13, 2024 10:07:31 PM
À : springbok/MLM2PRO-GSPro-Connector ***@***.***>
Cc : Charleybeat ***@***.***>; Author ***@***.***>
Objet : Re: [springbok/MLM2PRO-GSPro-Connector] Android Cast (Issue #83)


To clarify, are you still having problems or have you resolved all the issues? I'm adding a function that will display the Window titles of all open Windows to make it easier for people to find the correct value.

**Comment by Charleybeat** [comment]
Hi Etienne quick update
I installed the v1.02.03 (replaced my connector with those files).
Set up: Ipad direct connect and usb mirror with Airdroid Cast
No disconnect from rapsodo at all in 3 hours.

Only issue I have now is maybe 10% of the time I got wrong reading in the ROI.
Example; a chip is suposed to be 39 mph ballspeed is read 139 mph
Same for launch angle
Even if I do Verifiy I still have those errors happening

Thanks for your help so far!
Let me know if you have advice or you need me to test something




Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Etienne van Tonder ***@***.***>
Envoyé : Wednesday, March 13, 2024 10:58:51 PM
À : springbok/MLM2PRO-GSPro-Connector ***@***.***>
Cc : Charleybeat ***@***.***>; Author ***@***.***>
Objet : Re: [springbok/MLM2PRO-GSPro-Connector] Android Cast (Issue #83)


  1.  exputt: nothing was read into the connector
I reboot and then reconnect everything I did 2 holes and then nothing was going into the connector again. Haven’t found the solution, will try again tomorrow

When this happens check ExPutt make sure it hasn't lost sync, say when the camera is blocked or due the lighting issues. Also check the ROI's still look good. It should be very reliable.

  1.  ROI for launch angle : lots of errors
I need to rehit shots

Make sure you are running the mirror maximised, if not open ROI settings and AFTER it opens resize your mirror, hit 'Reset', set your ROI's, 'Verify', 'Save'

  1.  ROI for Ball speed : lots of incorrect reading
example : 39 is read 139 in the connector
Happening only when chipping with two digits.

If you are using v32 can you try the latest beta v1.02.03, download from here https://1drv.ms/u/s!Agx7aYfjrZJ8qE3aNlAl42fh91cD?e=W84U9N

**Comment by springbok** [comment]
The latest release provides a Bluetooth connector to the mlm so should overcome these issues.
