### ISSUE TITLE
Mevo spin axis

### ISSUE THREAD

**Issue by bjparker002** [springbok/MLM2PRO-GSPro-Connector#84]
Connector is reading all spin axis as slice access. I hit several draws and hooks to validate.

**Comment by springbok** [comment]
Not sure what you mean, can you provide more details of exactly what the problem is with examples and images.

**Comment by bjparker002** [comment]
The connector is passing both left and right spin axis to GSPro as right spin axis. I just re-validated. I hit several shots that show left spin axis in the GS App but were passed to GSPro as right spin.Sent from my iPadOn Mar 7, 2024, at 6:48 PM, Etienne van Tonder ***@***.***> wrote:﻿
Not sure what you mean, can you provide more details of exactly what the problem is with examples and images.

**Comment by bjparker002** [comment]
Here is an example. Left side spin in FS App. Ball launches right of target but comes back to be on line. Connector passes to GSPro as right spin. Ball starts right and goes farther right.Sent from my iPhoneOn Mar 10, 2024, at 11:49 AM, BJ Parker ***@***.***> wrote:﻿Here is an example. Left side spin in FS App. Ball launches right of target but comes back to be on line. Connector passes to GSPro as right spin. Ball starts right and goes farther right.<image0.jpeg><image1.jpeg><image2.jpeg>Sent from my iPhoneOn Mar 7, 2024, at 6:48 PM, Etienne van Tonder ***@***.***> wrote:﻿
Not sure what you mean, can you provide more details of exactly what the problem is with examples and images.

**Comment by wonder99** [comment]
I'm not seeing any photo attachments.  Can you also send a picture of your ROI page, so we can see where the boxes are relative to the digits?

**Comment by bjparker002** [comment]
Sent from my iPhoneOn Mar 10, 2024, at 2:28 PM, wonder99 ***@***.***> wrote:﻿
I'm not seeing any photo attachments.  Can you also send a picture of your ROI page, so we can see where the boxes are relative to the digits?

**Comment by bjparker002** [comment]
As an FYI, I had MLM2Pro selected in settings instead of Mevo. Changed and no issue. Works as it should.Sent from my iPadOn Mar 7, 2024, at 6:48 PM, Etienne van Tonder ***@***.***> wrote:﻿
Not sure what you mean, can you provide more details of exactly what the problem is with examples and images.

**Comment by springbok** [comment]
That would definitely make a difference as it would have been using the wrong OCR training file, good to hear its working now.

**Comment by bjparker002** [comment]
Sent from Mail for Windows From: wonder99Sent: Sunday, March 10, 2024 2:28 PMTo: springbok/MLM2PRO-GSPro-ConnectorCc: bjparker002; AuthorSubject: Re: [springbok/MLM2PRO-GSPro-Connector] Mevo spin axis (Issue #84) I'm not seeing any photo attachments. Can you also send a picture of your ROI page, so we can see where the boxes are relative to the digits?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
