### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Pikeonline1973** [springbok/MLM2PRO-GSPro-Connector#85]
My apologies I did not know where to add this as this is not an issue. this is a feature Request. Would it be possible to add a heartbeat signal to the program to keep the MLM2Pro from going to sleep? Absolutely love the connector! Cheers!

**Comment by springbok** [comment]
Not with the current publicly available versions, I have a new version with a direct Bluetooth connection that will keep it awake once you connect to it.

**Comment by springbok** [comment]
The new version of the app has been released, using the Bluetooth connector will stop the mlm from timing out.

**Comment by nommaz** [comment]
Could it also prevent windows from gping to sleep - perhaps by emulating a keypress on each detected shot?
