### ISSUE TITLE
Can't open the .exe file

### ISSUE THREAD

**Issue by Gaulfer** [springbok/MLM2PRO-GSPro-Connector#87]
Hello,

I downlaoded, unzipped and the exe file does not open. My system sends an error message saying that the file contains a virus. Also the icon does no look the same... see attached.
![Untitled](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/164764319/36c69398-05ef-485f-a223-aa668a6db532)
vs
![Previous exe file](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/164764319/445d005c-69a0-42e5-8343-61a6c11d151f)

**Comment by springbok** [comment]
Its not clear from the images what the problem is, is this the blue popup you get when running an unverified exe?

**Comment by springbok** [comment]
This is a known issue with pyinstaller generating false positives can you try this exe, I've rebuilt using the latest pyinstaller version. 

https://www.dropbox.com/scl/fi/n7ceyw6o0ehwnutsjrm7t/MLM2Pro-GSPro-Connector_rebuild.zip?rlkey=8xjo5iartapfba0mn9kb72tcb&st=bq4lc4cb&dl=0

**Comment by springbok** [comment]
I've rebuilt the exe using the latest version of pyinstaller, can you re-download the latest release and see if you still get the error, if you get a blue screen then select the option to allow the exe.

**Comment by springbok** [comment]
I've built this exe without pyinstaller do you mind testing if passes the anti-virus check 

https://www.dropbox.com/scl/fi/8y2p19l0ommh12har5cq4/MLM2Pro-GSPro-Connector_V1.04.01x.zip?rlkey=sg9pire6vqo1dbrunop1sgvcs&st=jb6qd2zv&dl=0

**Comment by Gaulfer** [comment]
I’ll test it with pleasure of course.

I’ll keep you posted.

I tried the last update update and it worked fine!

Thank you.

Eric

**Comment by springbok** [comment]
Ah ok so it worked ok for you when you re-downloaded the release?

**Comment by Gaulfer** [comment]
Yes, the one currently in the assets worked.

Thank you

Eric

**Comment by springbok** [comment]
Ok, good to hear it worked for you.

**Comment by Gaulfer** [comment]
Hi Etienne,
The connector w/o the pyinstaller works also well.

FYI, I have made a little change to the positioning of my BT dongle. Using
a very sophisticated hair elastic band from my daughter... ;) I have put it
even closer to the LM. It now is actually touching the back of it and it
improved the signal considerably; from -75 t0 -85 when it was just on the
floor below the LM to -40!
[image: image.png][image: image.png]

I can't believe how cheap Rapsodo went on radios?... Would have it been way
more expensive to use good ones?

Thanks again fro everything!

Cheers.

Eric

**Comment by wonder99** [comment]
Ya, it's frustrating about the radios, since I have a bad one.  But it could also just be poor hardware design, or poor manufacturing procedures that could drastically hinder the radio performance (e.g. did they ensure all metal parts are away from the antenna, is it the correct length, etc)
