### ISSUE TITLE
R10 calibration

### ISSUE THREAD

**Issue by MrSmith98** [springbok/MLM2PRO-GSPro-Connector#88]
Hi, R10 calibration seems absent, will this be added in future?

**Comment by springbok** [comment]
Can you give me more details, which calibration? I do a calibration when the connection is started.

**Comment by MrSmith98** [comment]
that's 1he one
, can not see it in the log that why I thought it to be an omission.

**Comment by MrSmith98** [comment]
Since there is a calibration I close the issue.
 Maybe you can add it to the log.
