### ISSUE TITLE
Windows 11 defender identifying  Trojan within application 

### ISSUE THREAD

**Issue by ROJACS** [springbok/MLM2PRO-GSPro-Connector#89]
Windows kept coming up with an error and would not install as what was identified a trojan virus

Love your work just thought I would report my issue

**Comment by springbok** [comment]
I uploaded a new exe earlier today, when did you download? If you can re-download the rehear files as a number of people have reported Defender is now happy with it.

**Comment by ROJACS** [comment]
It was around 11am AEST

**Comment by springbok** [comment]
If you don’t mind can you try this exe 

https://www.dropbox.com/scl/fi/8y2p19l0ommh12har5cq4/MLM2Pro-GSPro-Connector_V1.04.01x.zip?rlkey=sg9pire6vqo1dbrunop1sgvcs&st=jb6qd2zv&dl=0

**Comment by ROJACS** [comment]
Sure will be in a couple of days will let you know thanks
