### ISSUE TITLE
Connector App Window Closing

### ISSUE THREAD

**Issue by MadDasher** [springbok/MLM2PRO-GSPro-Connector#97]
Using GS Pro, WebCam with "balltracking", and Garmin R10.

Anyone experiencing an issue where the Connector app opens, IMMEDIATELY closes(you'll miss it if you're not watching), but the remaining apps(GS Pro, etc) all open correctly?  I then have to reselect the Connector app.  It opens and most of the time seems to work....but sometimes gets glitchy(presumably because I've now opened it twice).

Thx for any thoughts.

**Comment by wonder99** [comment]
Try setting the GSPRO path to GSPRO itself instead of the launcher:
![image](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/5347771/5a2e7abb-abf7-4294-9822-0752bceac5f5)

**Comment by MadDasher** [comment]
Yes, that did it. Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
