### ISSUE TITLE
Error When Launching the App

### ISSUE THREAD

**Issue by mmggppmgp** [springbok/MLM2PRO-GSPro-Connector#98]
![2024-05-11 22_29_33-Unhandled exception in script](https://github.com/springbok/MLM2PRO-GSPro-Connector/assets/169575379/5dabf146-1d27-4c60-b85a-349364121e68)

Some help would be great! Thank you so much.

**Comment by RocknRollGolf** [comment]
What LM are you using

**Comment by mmggppmgp** [comment]
I have an MLM2PRO updated to the latest firmware. I did run "Duwaynef" and it works fine. After debugging it for the last few hours it seems like it's trying to launch the "ball_tracking" breaks both builds.
